version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.1.0
  python: circleci/python@1.5.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/python:3.11
    # environment:
        # PYENV_ROOT: /home/circleci/.pyenv
        # PATH: /home/circleci/.pyenv/shims:/home/circleci/.pyenv/bin:$PATH


    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      # - run: pyenv install 3.10.2 # Or any other version of Python that you need
      # - run: pyenv global 3.10.2 # Set the global Python version to the one you just installed
      # - run: python --version # Verify that the correct Python version is being used
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: "Say hello"
          command: "echo Hello, World!"

      - run:
          name: "List Pip Packages"
          command: "pip list"
      - run:
          name: "Run Tests"
          command: |
            cd Assignment3
            flask run&
            coverage run -m pytest
            coverage report
      - coveralls/upload

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello